export const BRAND = {
  wordmark: "VESTA",
  footerBrand: "VESTA MODA",
  phrase: "Vista o que representa você.",
  instagramLabel: "Instagram",
  whatsappLabel: "WhatsApp",
  backTop: "Voltar ao topo ↑",
  promo: {
    text: "Peças únicas com curadoria · Frete para todo o Brasil",
  },
  hero: {
    kicker: "Curadoria contemporânea",
    titleLine: "VISTA O QUE",
    titleAccent: "representa você",
    description:
      "Curadoria de peças especiais para todos os estilos, histórias e formas de se expressar.",
    primaryCta: "Explorar curadoria",
    secondaryCta: "Conhecer a Vesta",
    image:
      "https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1600",
    imageAlt:
      "Mulher estilosa usando camisa oversized e óculos escuros em retrato de moda contemporânea.",
  },
  trust: [
    { label: "Maior rede de compradores", detail: "via celular" },
    { label: "Peças com curadoria", detail: "selecionadas à mão" },
    { label: "Pagamento seguro", detail: "Pix e cartão" },
    { label: "Envio rápido", detail: "para todo o Brasil" },
  ],
  bestSellers: {
    title: "BEST-SELLERS",
    tabs: ["Blazers", "Camisas", "Vestidos", "Sapatos", "Bolsas"] as const,
  },
  launches: {
    title: "LANÇAMENTOS",
  },
  categories: {
    title: "CATEGORIAS",
    chips: [
      {
        label: "Blazers",
        href: "/produtos?category=blazers",
        image: "/curadoria/pexels-photo-19584322.jpg",
      },
      {
        label: "Camisas",
        href: "/produtos?category=camisas",
        image: "/curadoria/pexels-photo-22441297.jpg",
      },
      {
        label: "Vestidos",
        href: "/produtos?category=vestidos",
        image: "/curadoria/pexels-photo-35907407.jpg",
      },
      {
        label: "Casacos",
        href: "/produtos?category=casacos",
        image: "/curadoria/pexels-photo-22805433.jpg",
      },
    ],
  },
  testimonials: {
    kicker: "Impressões",
    title: "Histórias em construção",
    items: [
      {
        quote:
          "Encontrei uma peça que parecia já fazer parte de mim. Essa é uma narrativa demonstrativa de como a experiência Vesta pode ser sentida.",
        author: "Cliente Vesta",
      },
      {
        quote:
          "A curadoria me ajudou a olhar para o meu estilo com mais liberdade. Exemplo ilustrativo, não uma avaliação verificada.",
        author: "Comunidade Vesta",
      },
      {
        quote:
          "Gostei de sentir que a moda aqui conversa com pessoas, e não com rótulos. Texto de exemplo para esta demonstração.",
        author: "Pessoa Vesta",
      },
    ],
  },
  faq: {
    kicker: "Dúvidas",
    title: "FAQ",
    items: [
      {
        q: "As peças da Vesta têm bom custo-benefício?",
        a: "Sim. Você investe em peças com curadoria de acabamento e presença — menos peças, mais impacto no look.",
      },
      {
        q: "Posso comprar pelo celular?",
        a: "Sim. A Vesta foi pensada para a maior rede de compradores via celular: navegue, reserve e finalize direto do aparelho.",
      },
      {
        q: "Como funcionam frete e troca?",
        a: "Enviamos para todo o Brasil com rastreio. Em caso de troca, fale conosco pelo WhatsApp dentro do prazo do pedido.",
      },
      {
        q: "As peças são únicas?",
        a: "Muitas sim. Por isso, garanta a sua escolha assim que se reconhecer nela — o estoque muda com a curadoria.",
      },
    ],
  },
  contact: {
    kicker: "Vamos conversar",
    title: "A sua história também inspira a Vesta.",
    text: "Conte o que você procura, compartilhe uma ideia ou deixe seu recado. Vamos receber sua mensagem com atenção.",
    name: "Nome",
    email: "E-mail",
    whatsapp: "WhatsApp",
    whatsappOptional: "(opcional)",
    message: "Mensagem",
    submit: "Enviar mensagem",
    disclaimer: "Ao enviar, sua mensagem é salva de forma privada para retorno da Vesta.",
  },
  bag: {
    kicker: "Sua seleção",
    title: "Sacola Vesta",
    empty: "Sua sacola está esperando uma escolha especial.",
    subtotal: "Subtotal",
    checkout: "Finalizar compra",
  },
  footer: {
    navTitle: "Navegue",
    serviceTitle: "Atendimento",
    serviceText: "A Vesta recebe cada mensagem com atenção e cuidado.",
    copy: "© 2026 VESTA MODA",
  },
  manifesto: {
    kicker: "Manifesto",
    title: "A Vesta é para você",
    description:
      "Não existe uma idade, um gênero ou um estilo certo para pertencer à Vesta. Existe a vontade de vestir algo que acompanhe quem você é — hoje, por inteiro.",
    pillars: [
      {
        n: "01",
        title: "Personalidade",
        text: "Peças que acompanham sua história, sem tentar encaixar você em uma só definição.",
      },
      {
        n: "02",
        title: "Curadoria",
        text: "Seleção atenta a acabamento, presença, versatilidade e tudo o que faz uma peça especial.",
      },
      {
        n: "03",
        title: "Bem-estar",
        text: "Vestir-se também é se sentir à vontade, confiante e reconhecido em seu próprio ritmo.",
      },
    ],
  },
  editorial: {
    kicker: "Vestir como gesto",
    title: "Escolha sentir.",
    text: "A roupa pode ser abrigo, memória, festa e presença. Escolha aquilo que faz você se reconhecer — sem regras prontas, com espaço para a sua própria narrativa.",
    cta: "Ver curadoria",
  },
  journal: {
    kicker: "Inspiração",
    title: "Diário Vesta",
    articles: [
      {
        category: "Curadoria",
        title: "Menos peças, mais histórias",
        text: "Um olhar sobre escolhas que resistem ao tempo e criam espaço para combinações mais pessoais.",
        image:
          "https://images.pexels.com/photos/5709661/pexels-photo-5709661.jpeg?auto=compress&cs=tinysrgb&w=800",
        alt: "Roupas femininas variadas em cabides de madeira em uma loja.",
      },
      {
        category: "Tendências",
        title: "O tempo das peças com presença",
        text: "Texturas, cortes e detalhes que transformam uma tendência passageira em escolha afetiva.",
        image:
          "https://images.pexels.com/photos/3755706/pexels-photo-3755706.jpeg?auto=compress&cs=tinysrgb&w=800",
        alt: "Casacos e gravatas elegantes em manequins de loja contemporânea.",
      },
      {
        category: "Comportamento",
        title: "Vestir a própria linguagem",
        text: "Uma reflexão sobre moda como linguagem cotidiana, com liberdade para mudar de ideia e de forma.",
        image:
          "https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg?auto=compress&cs=tinysrgb&w=800",
        alt: "Pessoa olhando roupas em cabides dentro de boutique estilosa.",
      },
    ],
  },
  catalog: {
    kicker: "Acervo",
    title: "Curadoria",
    note: "Peças escolhidas uma a uma. A maioria existe em uma única unidade.",
    cta: "Ver todas as peças",
    searchLabel: "Buscar",
    searchPlaceholder: "Buscar peça",
    categoryLabel: "Categoria",
    styleLabel: "Estilo",
    sortLabel: "Ordenar",
    priceLabel: "Preço:",
    emptyTitle: "Nenhuma peça encontrada",
    emptyText: "Tente outro termo ou limpe os filtros.",
    clearFilters: "Limpar filtros",
  },
} as const;

export type ShopPiece = {
  slug: string;
  name: string;
  category: string;
  style: string;
  priceCents: number;
  compareAtCents: number;
  brand: string;
  size: string;
  color: string;
  colors: { name: string; hex: string }[];
  rating: number;
  reviews: number;
  badge?: string;
  discountLabel?: string;
  isLaunch?: boolean;
  isBestSeller?: boolean;
  condition: "NEW_WITH_TAG" | "EXCELLENT" | "VERY_GOOD" | "GOOD" | "VINTAGE";
  categorySlug: string;
  description: string;
  image: string;
  gallery?: string[];
  alt: string;
};

export const FEATURED_PIECES: ShopPiece[] = [
  {
    slug: "blazer-siena",
    name: "Blazer Siena",
    category: "Blazers",
    style: "Social",
    priceCents: 36990,
    compareAtCents: 39990,
    brand: "Siena",
    size: "M",
    color: "Camelo",
    colors: [
      { name: "Camelo", hex: "#C4A484" },
      { name: "Champagne", hex: "#E8D5B7" },
      { name: "Preto", hex: "#1a1a1a" },
      { name: "Vinho", hex: "#6B1C16" },
    ],
    rating: 4.9,
    reviews: 387,
    badge: "Mais Vendidos",
    discountLabel: "8% OFF",
    isBestSeller: true,
    condition: "VERY_GOOD",
    categorySlug: "blazers",
    description: "Blazer marrom elegante, ombro marcado e caimento de boutique.",
    image: "/curadoria/pexels-photo-19584322.jpg",
    alt: "Blazer marrom elegante em manequim de boutique.",
  },
  {
    slug: "trench-soleil",
    name: "Trench Soleil",
    category: "Casacos",
    style: "Casual",
    priceCents: 41990,
    compareAtCents: 47990,
    brand: "Soleil",
    size: "M",
    color: "Khaki",
    colors: [
      { name: "Khaki", hex: "#C3B091" },
      { name: "Preto", hex: "#1a1a1a" },
      { name: "Caramelo", hex: "#A67B5B" },
    ],
    rating: 4.88,
    reviews: 177,
    badge: "Mais Vendidos",
    discountLabel: "13% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "EXCELLENT",
    categorySlug: "casacos",
    description: "Trench coat urbano, óculos escuros e corte com memória de rua.",
    image: "/curadoria/pexels-photo-22805433.jpg",
    alt: "Mulher com trench coat e óculos escuros em estilo urbano.",
  },
  {
    slug: "blazer-nilo",
    name: "Blazer Nilo",
    category: "Blazers",
    style: "Social",
    priceCents: 38990,
    compareAtCents: 42990,
    brand: "Nilo",
    size: "G",
    color: "Preto",
    colors: [
      { name: "Preto", hex: "#1a1a1a" },
      { name: "Champagne", hex: "#E8D5B7" },
      { name: "Vinho", hex: "#6B1C16" },
    ],
    rating: 4.97,
    reviews: 112,
    discountLabel: "9% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "EXCELLENT",
    categorySlug: "blazers",
    description: "Blazer estruturado em tom escuro, presença de alfaiataria.",
    image: "https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "Peça de alfaiataria em cabide de boutique.",
  },
  {
    slug: "camisa-iris",
    name: "Camisa Íris",
    category: "Camisas",
    style: "Essencial",
    priceCents: 19990,
    compareAtCents: 22990,
    brand: "Íris",
    size: "M",
    color: "Off-white",
    colors: [
      { name: "Off-white", hex: "#F5F0E8" },
      { name: "Azul", hex: "#2C3E6B" },
      { name: "Preto", hex: "#1a1a1a" },
    ],
    rating: 4.9,
    reviews: 49,
    discountLabel: "13% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "NEW_WITH_TAG",
    categorySlug: "camisas",
    description: "Camisa de linho minimalista, botões à mostra e caimento leve.",
    image: "/curadoria/pexels-photo-22441297.jpg",
    alt: "Camisa de linho minimalista em cabide de madeira.",
  },
  {
    slug: "camisa-luna",
    name: "Camisa Luna",
    category: "Camisas",
    style: "Casual",
    priceCents: 21990,
    compareAtCents: 24990,
    brand: "Luna",
    size: "P",
    color: "Champagne",
    colors: [
      { name: "Champagne", hex: "#E8D5B7" },
      { name: "Off-white", hex: "#F5F0E8" },
      { name: "Preto", hex: "#1a1a1a" },
    ],
    rating: 4.85,
    reviews: 28,
    discountLabel: "12% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "EXCELLENT",
    categorySlug: "camisas",
    description: "Camisa leve com caimento fluido e acabamento limpo.",
    image: "https://images.pexels.com/photos/5709661/pexels-photo-5709661.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "Camisas e peças leves em cabides.",
  },
  {
    slug: "vestido-aurora",
    name: "Vestido Aurora",
    category: "Vestidos",
    style: "Festa",
    priceCents: 41990,
    compareAtCents: 47990,
    brand: "Aurora",
    size: "P",
    color: "Vinho",
    colors: [
      { name: "Vinho", hex: "#6B1C16" },
      { name: "Preto", hex: "#1a1a1a" },
      { name: "Champagne", hex: "#E8D5B7" },
    ],
    rating: 5.0,
    reviews: 71,
    discountLabel: "13% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "EXCELLENT",
    categorySlug: "vestidos",
    description: "Vestido de festa com manga bufante e presença dramática.",
    image: "/curadoria/pexels-photo-35907407.jpg",
    alt: "Pessoa usando vestido elegante em iluminação dramática.",
  },
  {
    slug: "vestido-clara",
    name: "Vestido Clara",
    category: "Vestidos",
    style: "Casual",
    priceCents: 29990,
    compareAtCents: 34990,
    brand: "Clara",
    size: "M",
    color: "Areia",
    colors: [
      { name: "Areia", hex: "#D4C4A8" },
      { name: "Preto", hex: "#1a1a1a" },
    ],
    rating: 4.92,
    reviews: 41,
    discountLabel: "14% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "VERY_GOOD",
    categorySlug: "vestidos",
    description: "Vestido fluido em tom areia, ideal para o dia a dia com presença.",
    image: "https://images.pexels.com/photos/985635/pexels-photo-985635.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "Vestido feminino em tecido leve.",
  },
  {
    slug: "sapato-roma",
    name: "Sapato Roma",
    category: "Sapatos",
    style: "Social",
    priceCents: 28990,
    compareAtCents: 31990,
    brand: "Roma",
    size: "40",
    color: "Caramelo",
    colors: [
      { name: "Caramelo", hex: "#A67B5B" },
      { name: "Preto", hex: "#1a1a1a" },
    ],
    rating: 4.93,
    reviews: 84,
    discountLabel: "9% OFF",
    isBestSeller: true,
    condition: "VINTAGE",
    categorySlug: "sapatos",
    description: "Sapato social de couro vintage, palmilha original e sola honesta.",
    image: "/curadoria/pexels-photo-298863.jpg",
    alt: "Sapatos de couro marrom em loja de roupas.",
  },
  {
    slug: "sapato-leo",
    name: "Sapato Léo",
    category: "Sapatos",
    style: "Casual",
    priceCents: 24990,
    compareAtCents: 27990,
    brand: "Léo",
    size: "38",
    color: "Preto",
    colors: [
      { name: "Preto", hex: "#1a1a1a" },
      { name: "Caramelo", hex: "#A67B5B" },
    ],
    rating: 4.8,
    reviews: 56,
    discountLabel: "11% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "EXCELLENT",
    categorySlug: "sapatos",
    description: "Sapato de couro preto com sola confortável e linha clássica.",
    image: "https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "Par de sapatos escuros em close.",
  },
  {
    slug: "bolsa-alba",
    name: "Bolsa Alba",
    category: "Bolsas",
    style: "Casual",
    priceCents: 27990,
    compareAtCents: 29990,
    brand: "Alba",
    size: "Único",
    color: "Caramelo",
    colors: [
      { name: "Caramelo", hex: "#A67B5B" },
      { name: "Preto", hex: "#1a1a1a" },
      { name: "Champagne", hex: "#E8D5B7" },
    ],
    rating: 5.0,
    reviews: 32,
    discountLabel: "7% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "EXCELLENT",
    categorySlug: "bolsas",
    description: "Bolsa de couro texturizado, alça curta e presença casual.",
    image: "/curadoria/pexels-photo-28773220.png",
    alt: "Bolsa de couro marrom com textura sofisticada apoiada sobre pedra.",
  },
  {
    slug: "bolsa-mira",
    name: "Bolsa Mira",
    category: "Bolsas",
    style: "Social",
    priceCents: 34990,
    compareAtCents: 38990,
    brand: "Mira",
    size: "Único",
    color: "Preto",
    colors: [
      { name: "Preto", hex: "#1a1a1a" },
      { name: "Vinho", hex: "#6B1C16" },
    ],
    rating: 4.95,
    reviews: 19,
    discountLabel: "10% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "NEW_WITH_TAG",
    categorySlug: "bolsas",
    description: "Bolsa estruturada em tom escuro, ideal para looks com presença.",
    image: "https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "Bolsa elegante em close.",
  },
  {
    slug: "casaco-duplo",
    name: "Casaco Duplo",
    category: "Casacos",
    style: "Casual",
    priceCents: 39990,
    compareAtCents: 44990,
    brand: "Duplo",
    size: "M",
    color: "Caramelo",
    colors: [
      { name: "Caramelo", hex: "#A67B5B" },
      { name: "Khaki", hex: "#C3B091" },
      { name: "Preto", hex: "#1a1a1a" },
    ],
    rating: 4.9,
    reviews: 63,
    discountLabel: "11% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "VERY_GOOD",
    categorySlug: "casacos",
    description: "Casaco com caimento amplo e acabamento de atelier.",
    image: "https://images.pexels.com/photos/3755706/pexels-photo-3755706.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "Casacos elegantes em manequins.",
  },
  {
    slug: "blazer-paris",
    name: "Blazer Paris",
    category: "Blazers",
    style: "Social",
    priceCents: 35990,
    compareAtCents: 39990,
    brand: "Paris",
    size: "P",
    color: "Champagne",
    colors: [
      { name: "Champagne", hex: "#E8D5B7" },
      { name: "Camelo", hex: "#C4A484" },
      { name: "Preto", hex: "#1a1a1a" },
    ],
    rating: 4.91,
    reviews: 204,
    badge: "Mais Vendidos",
    discountLabel: "10% OFF",
    isBestSeller: true,
    condition: "EXCELLENT",
    categorySlug: "blazers",
    description: "Blazer champagne com ombro marcado e caimento alongado.",
    image: "https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "Look com blazer em tom claro.",
  },
  {
    slug: "blazer-roma",
    name: "Blazer Roma",
    category: "Blazers",
    style: "Social",
    priceCents: 37990,
    compareAtCents: 42990,
    brand: "Roma",
    size: "M",
    color: "Vinho",
    colors: [
      { name: "Vinho", hex: "#6B1C16" },
      { name: "Preto", hex: "#1a1a1a" },
      { name: "Caramelo", hex: "#A67B5B" },
    ],
    rating: 4.94,
    reviews: 156,
    discountLabel: "12% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "VERY_GOOD",
    categorySlug: "blazers",
    description: "Blazer vinho estruturado, presença de alfaiataria clássica.",
    image: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "Mulher com blazer escuro em estúdio.",
  },
  {
    slug: "blazer-lisboa",
    name: "Blazer Lisboa",
    category: "Blazers",
    style: "Casual",
    priceCents: 34990,
    compareAtCents: 38990,
    brand: "Lisboa",
    size: "G",
    color: "Caramelo",
    colors: [
      { name: "Caramelo", hex: "#A67B5B" },
      { name: "Khaki", hex: "#C3B091" },
      { name: "Preto", hex: "#1a1a1a" },
    ],
    rating: 4.87,
    reviews: 98,
    badge: "Mais Vendidos",
    discountLabel: "10% OFF",
    isBestSeller: true,
    condition: "EXCELLENT",
    categorySlug: "blazers",
    description: "Blazer caramelo versátil para o dia a dia com presença.",
    image: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "Blazer em tom terroso em look urbano.",
  },
  {
    slug: "blazer-miami",
    name: "Blazer Miami",
    category: "Blazers",
    style: "Social",
    priceCents: 39990,
    compareAtCents: 45990,
    brand: "Miami",
    size: "M",
    color: "Preto",
    colors: [
      { name: "Preto", hex: "#1a1a1a" },
      { name: "Azul", hex: "#2C3E6B" },
      { name: "Cinza", hex: "#6B6660" },
    ],
    rating: 5.0,
    reviews: 88,
    discountLabel: "13% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "NEW_WITH_TAG",
    categorySlug: "blazers",
    description: "Blazer preto impecável, corte moderno e acabamento premium.",
    image: "https://images.pexels.com/photos/7671166/pexels-photo-7671166.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "Blazer preto em manequim de loja.",
  },
  {
    slug: "blazer-tokyo",
    name: "Blazer Tóquio",
    category: "Blazers",
    style: "Casual",
    priceCents: 36990,
    compareAtCents: 40990,
    brand: "Tóquio",
    size: "P",
    color: "Cinza",
    colors: [
      { name: "Cinza", hex: "#6B6660" },
      { name: "Preto", hex: "#1a1a1a" },
      { name: "Champagne", hex: "#E8D5B7" },
    ],
    rating: 4.89,
    reviews: 67,
    discountLabel: "10% OFF",
    isBestSeller: true,
    condition: "EXCELLENT",
    categorySlug: "blazers",
    description: "Blazer cinza com modelagem leve e caimento contemporâneo.",
    image: "https://images.pexels.com/photos/6311392/pexels-photo-6311392.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "Look com blazer em tom neutro.",
  },
  {
    slug: "camisa-nora",
    name: "Camisa Nora",
    category: "Camisas",
    style: "Essencial",
    priceCents: 18990,
    compareAtCents: 21990,
    brand: "Nora",
    size: "M",
    color: "Branco",
    colors: [
      { name: "Branco", hex: "#F5F0E8" },
      { name: "Azul", hex: "#2C3E6B" },
      { name: "Preto", hex: "#1a1a1a" },
    ],
    rating: 4.86,
    reviews: 44,
    discountLabel: "14% OFF",
    isBestSeller: true,
    isLaunch: true,
    condition: "NEW_WITH_TAG",
    categorySlug: "camisas",
    description: "Camisa branca clássica com botões discretos e caimento limpo.",
    image: "https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&w=800",
    gallery: [
      "https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/7671168/pexels-photo-7671168.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/6311392/pexels-photo-6311392.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    alt: "Camisa branca em close.",
  },
  {
    slug: "vestido-sofia",
    name: "Vestido Sofia",
    category: "Vestidos",
    style: "Festa",
    priceCents: 44990,
    compareAtCents: 49990,
    brand: "Sofia",
    size: "P",
    color: "Preto",
    colors: [
      { name: "Preto", hex: "#1a1a1a" },
      { name: "Vinho", hex: "#6B1C16" },
    ],
    rating: 4.98,
    reviews: 53,
    badge: "Mais Vendidos",
    discountLabel: "10% OFF",
    isBestSeller: true,
    condition: "EXCELLENT",
    categorySlug: "vestidos",
    description: "Vestido preto com presença, ideal para ocasiões especiais.",
    image: "https://images.pexels.com/photos/985635/pexels-photo-985635.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "Vestido elegante em tecido fluido.",
  },
];
